language: go
go:
  - 1.8.x
sudo: required
install:
  - go get github.com/spf13/hugo
script: hugo
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.milhouse.uk
  region: eu-west-1
  endpoint: www.milhouse.uk.s3-website-eu-west-1.amazonaws.com
  local-dir: public
  skip_cleanup: true
  on:
    repo: patrickn/milhouseuk-hugo
notifications:
  email:
    on_failure: always
