title = "Milhouse Ltd."
baseurl = "https://www.milhouse.uk/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishdir = "public"
author = "Patrick Neave"
pygmentsuseclasses = true
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
home = "home/:slug/"

[params]
author = "Patrick"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Milhouse Ltd."
logofile = "img/logo.png"
faviconfile = "img/favicon.ico"
highlightjs = true
lang = "en"

github = "https://github.com/MilhouseLtd"
email = "hello@milhouse.uk"
twitter = "https://twitter.com/milhouseltd"
