title = "Milhouse Ltd."
baseurl = "https://www.milhouse.uk/"
theme = "minimal"
languageCode = "en-GB"
disqusshortname = ""
# googleAnalytics = "UA-87135551-3"
enableRobotsTXT = true

[params]
   author = "Milhouse Ltd."
   description = "Software Development and Consultancy services based in Bristol, UK. Unix, Linux, iOS, macOS and embedded development."
   githubUsername = "MilhouseLtd"
   accent = "red"
   showBorder = true
   backgroundColor = "white"
   font = "Raleway" # should match the name on Google Fonts!
   highlight = true
   highlightStyle = "atelier-dune-light"
   highlightLanguages = ["cpp", "go", "swift"]    # Check these exist at github.com/isagalaev/highlight.js/tree/master/src/languages
   ProfilePicture = "/img/milhouse-logo-1200x485.png"
   faviconfile = "img/favicon.ico"

[[menu.main]]
   url = "/"
   name = "Home"
   weight = 1

# [[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 2

[[menu.main]]
   url = "/Contact/"
   name = "Contact"
   weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
   url = "https://mas.to/@neavey/"
   name = "fab fa-mastodon"
   weight = 3

[[menu.icon]]
   url = "mailto:pneave@milhouse.uk"
   name = "fas fa-envelope"
   weight = 1

[[menu.icon]]
   url = "https://github.com/MilhouseLtd/"
   name = "fab fa-github"
   weight = 2

[[menu.icon]]
   url = "https://www.stackoverflow.com/users/11884/patrick/"
   name = "fab fa-stack-overflow"
   weight = 4
